name: QAt CI
on: [push, pull_request]

jobs:
  test-chromium:
    name: Test Chromium (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Cache NPM Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install NPM Dependencies
        run: npm ci

      - name: Install Chromium Playwright
        run: npx playwright install chromium && npx playwright install-deps chromium

      - name: Run Chatbot E2E Tests 
        run: npx playwright test chatbot/basicFunctional.spec.ts --headed --project=1920x1080
        
      - name: Run Box E2E Tests 
        run: npx playwright test chatbot/box.spec.ts --project=1920x1080
        
      - name: Run Box inside Campaign E2E Tests 
        run: npx playwright test chatbot/boxCamp.spec.ts --project=1920x1080

      - name: Run Button E2E Tests 
        run: npx playwright test chatbot/button.spec.ts --project=1920x1080

      - name: Run Button inside Campaign E2E Tests 
        run: npx playwright test chatbot/buttonCamp.spec.ts --project=1920x1080  
        
      - name: Run Variables E2E Tests 
        run: npx playwright test chatbot/variableCreate.spec.ts --project=1920x1080

      - name: Run Search E2E Tests 
        run: npx playwright test chatbot/search.spec.ts --project=1920x1080

      - name: Run IMG from Local E2E Tests 
        run: npx playwright test chatbot/imglocal.spec.ts --project=1920x1080

      - name: Run AFP Camp E2E Tests 
        run: npx playwright test campañas/afpChat.spec.ts --project=1920x1080

      - name: Run Tulum Camp E2E Tests 
        run: npx playwright test campañas/tulumsmartsurvey.spec.ts --project=1920x1080
        
      - name: Run FCI Camp E2E Tests 
        run: npx playwright test campañas/fci.spec.ts --project=1920x1080     

  test-webkit:
      name: Test WebKit (MacOS)
      runs-on: macos-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Setup Node.js
          uses: actions/setup-node@v1
          with:
            node-version: 16

        - name: Cache NPM Dependencies
          uses: actions/cache@v2
          with:
            path: ~/.npm
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            restore-keys: ${{ runner.os }}-node-

        - name: Install NPM Dependencies
          run: npm ci

        - name: Install WebKit Playwright
          run: npx playwright install webkit && npx playwright install-deps webkit

        - name: Run Chatbot E2E Tests 
          run: npx playwright test chatbot/basicFunctional.spec.ts --project=webkit
        
        - name: Run Box E2E Tests 
          run: npx playwright test chatbot/box.spec.ts --project=webkit
          
        - name: Run Botton with Campaign E2E Tests 
          run: npx playwright test chatbot/boxCamp.spec.ts --project=webkit

        - name: Run Button E2E Tests 
          run: npx playwright test chatbot/button.spec.ts --project=webkit

        - name: Run Button inside Campaigh E2E Tests 
          run: npx playwright test chatbot/buttonCamp.spec.ts --project=webkit  
          
        - name: Run Variables E2E Tests 
          run: npx playwright test chatbot/variableCreate.spec.ts --project=webkit

        - name: Run Search E2E Tests 
          run: npx playwright test chatbot/search.spec.ts --project=webkit
        
        - name: Run AFP Camp E2E Tests 
          run: npx playwright test campañas/afpChat.spec.ts --project=webkit

        - name: Run Tulum Camp E2E Tests 
          run: npx playwright test campañas/tulumsmartsurvey.spec.ts --project=webkit

        - name: Run FCI Camp E2E Tests 
          run: npx playwright test campañas/fci.spec.ts --project=webkit

