name: QAt CI
on: [push, pull_request]

jobs:
  test-chromium:
    name: Test Chromium (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Cache NPM Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install NPM Dependencies
        run: npm ci

      - name: Install Chromium Playwright
        run: npx playwright install chromium && npx playwright install-deps chromium

      - name: Run Chatbot E2E Tests 
        run: npx playwright test chatbot/basicFunctional.spec.ts --headed --project=1920x1080
        
      - name: Run Box E2E Tests 
        run: npx playwright test chatbot/box.spec.ts --headed --project=1920x1080
        
      - name: Run Button E2E Tests 
        run: npx playwright test chatbot/box.spec.ts --headed --project=1920x1080
        
      - name: Run Variables E2E Tests 
        run: npx playwright test chatbot/variableCreate.spec.ts --headed --project=1920x1080
      
      
