name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npx webpack
    - name: Install NPM Dependencies
      run: npm ci --legacy-peer-deps

    - name: Install Chromium Playwright
      run: npx playwright install chromium && npx playwright install-deps chromium

    - name: Run Chromium E2E Tests (Service Worker)
      run: npm run test.chromium
